### ISSUE TITLE
Question about using reflectance map as the output

### ISSUE THREAD

**Issue by QiuJueqin** [fengzhang427/HEP#2]
Hi, the HE prior is awesome, but I am kind of confused about directly using (denoised) reflectance map as the final output, without combined with the (enhanced) illumination map. In most low-light enhancement methods, to my knowledge, they separately enhance the reflectance map and the illumination map, and multiply them to construct the final enhanced image. I am wondering if it is a intended design? Will the output be over-brighten?

**Comment by fengzhang427** [comment]
Thanks for your comments. Our approach is inspired by the traditional retinex algorithm, according to the principles of the traditional retinex algorithm, the reflectance map can be regarded as the intrinsic property of the image, so we believe that the reflectance map can be directly used as the enhanced output image. The illumination map is just the reflection intensity of the light source on the object. Adjusting the illumination map can somehow make the image brightness more natural, but the adjustment is not generalizable and cannot be used in all nighttime environments.
